### ISSUE TITLE
Anchor certificates not working on iOS

### ISSUE THREAD

**Issue by alexrainman** [tranb3r/SecureHttpClient#9] opened 2019-01-17 19:01 UTC
If your certificate is self-signed, this line:

```cs
challenge.ProtectionSpace.ServerSecTrust.SetAnchorCertificates(_trustedRoots);
```

doesn't work.

**Comment by tranb3r** [comment] 2019-01-21 08:36
Any idea for a fix ?

**Comment by alexrainman** [comment] 2019-01-21 13:47
@tranb3r I have been researching but nothing yet.

**Comment by tranb3r** [comment] 2022-07-25 09:32
I'm closing this issue for now since I've been unable to reproduce your issue.
Do not hesitate to reopen it with more details if you still need a fix.
Thanks

**Closed by tranb3r** 2022-07-25 09:32 UTC
